### PR TITLE
WordPress compatibility fixes

### PR DESCRIPTION
**Pull request by paulschreiber**
This cleans up the code to meet the [WordPress Coding Standards](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards):
- Yoda conditions
- Strict equality checks
- Input validation and sanitization
- snake_case variable and method names
- whitespace fixes
- use of wp_xyz() helper functions when they exist
- creation of a new HTTP method that uses WordPress helpers.

Done as we're a [WordPress VIP](https://vip.wordpress.com/documentation/vip/best-practices/wordpress-coding-standards/) customer and we want it to pass review.

The overall diff looks like the whole file changed (due to whitespace and renaming). Look over the individual commits to review.

### CODE REVIEW

**Comment by silverman63** [comment]
Hi Paul, thanks for making the pull request.

Our [official Wordpress integration](https://github.com/sailthru/sailthru-wordpress-plugin) has been accepted by Wordpress VIP and includes a copy of the Sailthru client library. Have you tried using this copy before?

Many of these changes are specific to Wordpress and non-conventional outside of WordPress, and there are many PHP platforms that make similar recommendations/requirements for using their wrappers for HTTP, cookies, etc. I'd like to suggest that you take required changes (HTTP requests, wp_json_encode, etc) and implement them in a wp-client child class in a new integrations folder in this repo.

**Comment by silverman63** [comment]
Hi @paulschreiber, I didn't see a comment from you on the previous response. Another solution I'd feel comfortable offering is to add a link to your repo as an Unofficial Fork in our README.

**Comment by paulschreiber** [comment]
I like the subclass idea. It's on my to-do list for later. What about the rest of the changes?

**Comment by silverman63** [comment]
@paulschreiber which changes are you referring to? Class naming standards are currently PSR-0 compliant. Besides that, I'm not sure sure how to fully separate Wordpress compatability / yoda / etc from other changes.

**Comment by paulschreiber** [comment]
Not silencing errors, yoda conditions, validation and sanitization, etc. are individual commits.

**Comment by paulschreiber** [comment]
Also:
> As of 2014-10-21 PSR-0 has been marked as deprecated

**Comment by silverman63** [comment]
@paulschreiber The validation+sanitization seems directly tied to WP, and it's hard to cherry-pick out what would be client specific vs. the specific WP client. I'd prefer we start a new PR or modify the commits in this to reflect exactly what changes would be made where.

I've tried to look at what I can. Here are some comments:
- Yoda conditions are not universally used. While I'm OK with those in the Wordpress class, I'm not comfortable changing the code style of the client as a whole. The majority of those who might work with, update, and improve this client library will not be used to them, and any errors should anyways be caught in unit tests. 
- File names: I'm worried about backwards compatibility and pre-existing integrations. Will have to research further, but I'm guessing it's a no.
- Will have to look into the error suppression on fopen.
- Adding the array option for parse_rate_limit_headers requires a unit test.
- I don't see a compelling reason for the switch to snake case. Symfony and Zend use camel case, as do most developers working on this library. Once again, could be used in the WP client.

**Comment by silverman63** [comment]
Hi @paulschreiber I haven't from you on this in a while. I'm going to close this PR for now. While the discussion is valid, we wouldn't be using the current implementation. Feel free to open a GitHubissue or contact us about your wordpress concerns at integrations@sailthru.com.

**Pull request closed without merging**
