### PR TITLE
Code style checking

### PR DESCRIPTION
**Pull request by rossmotley**
Adding the [PHP Code Standards Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) to the repository is nice because it means that new code is automatically checked against a defined code standard - and it will fix any issues automatically so it doesn't get in the way of development.

I'm not sure what code style the repo wants to follow, but PSR-2 seems like a good place to start.

### CODE REVIEW

**Comment by silverman63** [comment]
Hi @rossmotley, sorry for delay. Will take a look into this.

**Comment by rossmotley** [comment]
@silverman63 if you decide you like the idea I'll need to make a new PR and re-run the fixer against it, as right now the things added to master since this PR was created are failing the code style checks.

**Comment by silverman63** [comment]
@rossmotley appreciate the submission. I've been looking into it, and we have an internal style guide that doesn't quite fit to a PSR. Might look into PSR-1, though. Like what you did the Travis scripts. So I'd say hold off for now. This also isn't a breaking change, so can gladly work on it after 2.0.0 release.

**Comment by rossmotley** [comment]
@silverman63 Okay then, I think it's a good thing to adopt some sort of automatically-enforced standard, as it makes it easier to check that PRs etc. meet it!

**Pull request closed without merging**
