### PR TITLE
The isset check needs to be !empty

### PR DESCRIPTION
**Pull request by yavorm**
The `isset` check fails when `$json['error']` is set to `false`, which is sometimes the case.

### CODE REVIEW

**Comment by yavorm** [comment]
Looks like the hhvm test failed on master too.

**Comment by silverman63** [comment]
Hey @yavorm, thanks for the PR.

I've been notified that there's an issue with the Travis image for HHVM, and need to update the image.

What cases have you seen the API return an empty error string?

**Comment by yavorm** [comment]
`getJobStatus` is returning `false ` in that key, not a string. Sorry, we fixed this in our fork a while back and I had forgotten what the specific response was. I'm submitting this PR now so we can potentially get rid of our fork and start using this repo.

**Comment by yavorm** [comment]
Updated the PR description too.

**Comment by yavorm** [comment]
@silverman63 Please let me know once you have time to evaluate/merge this PR. Thank you!

**Comment by silverman63** [comment]
Hi @yavorm, will let you know. Thanks for your patience.

**Comment by yavorm** [comment]
@silverman63 Can we try to re-run the tests and merge this fix?

**Comment by silverman63** [comment]
@yavorm will take care this week. Will address #73, let yours retest, and merge. I'm not sure I can guarantee an official release just yet, but it will be in master.

**Comment by silverman63** [comment]
@yavorm if you pull the latest master change, the test should pass for HHVM.

**Comment by yavorm** [comment]
Thank you @silverman63, passed!

**Pull request merged**
